### ISSUE TITLE
Support multi-arch and manifest

### ISSUE THREAD

**Issue by gutenye** [linuxserver/docker-rutorrent-armhf#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Docker supports [multi-arch images](https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6).

It's much easy for users to pull one `linuxserver/rutorrent` image and docker will figure out the correct image to pull for you. For example, pull `linuxserver/rutorrent` for x86_64,  and pull`lsioarmhf/rutorrent` for arm.

Official images are already [supporting this](https://github.com/docker-library/official-images#architectures-other-than-amd64)

**Comment by tobbenb** [comment]
I'm not sure using an experimental function of docker is the way to go now.

**Comment by j0nnymoe** [comment]
This is something that would take a lot of time to do due to our large fleet of containers. Not saying this isn't something we wont do but we would need to plan it etc. Plus as @tobbenb mentioned, we don't really want to put an experimental function in our containers.
